import os
import django
import urllib.request
import tempfile

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()

from django.core.files import File
from apps.products.models import Category, Product, ProductVariant, ProductImage
from apps.accounts.models import CustomUser

admin = CustomUser.objects.filter(role='admin').first()
if not admin:
    print('No admin found. Run createsuperuser first.')
    exit()


def download_image(url, filename):
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req, timeout=20) as response:
            with tempfile.NamedTemporaryFile(delete=False, suffix='.jpg') as tmp:
                tmp.write(response.read())
                return tmp.name
    except Exception as e:
        print(f'  Image download failed: {e}')
        return None


# ── Categories ────────────────────────────────────────────────

cat_data = [
    {
        'name': 'Men',
        'slug': 'men',
        'image_url': 'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600&auto=format&fit=crop&q=80',
        'image_name': 'cat-men.jpg',
    },
    {
        'name': 'Women',
        'slug': 'women',
        'image_url': 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&auto=format&fit=crop&q=80',
        'image_name': 'cat-women.jpg',
    },
    {
        'name': 'Kids',
        'slug': 'kids',
        'image_url': 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=600&auto=format&fit=crop&q=80',
        'image_name': 'cat-kids.jpg',
    },
    {
        'name': 'Accessories',
        'slug': 'accessories',
        'image_url': 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
        'image_name': 'cat-accessories.jpg',
    },
]

cats = {}
for c in cat_data:
    cat, created = Category.objects.get_or_create(
        slug=c['slug'],
        defaults={'name': c['name'], 'is_active': True}
    )
    # Download and save category image
    if created or not cat.image:
        tmp = download_image(c['image_url'], c['image_name'])
        if tmp:
            with open(tmp, 'rb') as f:
                cat.image.save(c['image_name'], File(f), save=True)
            os.unlink(tmp)
            print(f'Category image saved: {cat.name}')
    cats[c['slug']] = cat
    print(f'Category ready: {cat.name}')


# ── Products ──────────────────────────────────────────────────

products_data = [
    # ── MEN ──────────────────────────────────────────────────
    {
        'name': 'Classic White Linen Shirt',
        'slug': 'classic-white-linen-shirt',
        'description': 'A timeless white linen shirt perfect for any occasion. Lightweight and breathable.',
        'price': 189.00, 'gender': 'men', 'brand': 'Essentials',
        'category_key': 'men', 'tags': 'casual, summer, lightweight, linen, white',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&auto=format&fit=crop&q=80',
        'image_name': 'white-linen-shirt.jpg',
        'variants': [('S','White'),('M','White'),('L','White'),('XL','White')],
    },
    {
        'name': 'Tailored Black Blazer',
        'slug': 'tailored-black-blazer',
        'description': 'Sharp and sophisticated black blazer for formal and smart casual occasions.',
        'price': 450.00, 'gender': 'men', 'brand': 'Noir',
        'category_key': 'men', 'tags': 'formal, office, smart, blazer, black',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
        'image_name': 'black-blazer.jpg',
        'variants': [('S','Black'),('M','Black'),('L','Black'),('XL','Black')],
    },
    {
        'name': 'Slim Fit Chinos',
        'slug': 'slim-fit-chinos',
        'description': 'Modern slim fit chinos in khaki. Versatile for work and weekend.',
        'price': 175.00, 'gender': 'men', 'brand': 'Craft',
        'category_key': 'men', 'tags': 'chinos, slim, khaki, smart casual',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&auto=format&fit=crop&q=80',
        'image_name': 'slim-chinos.jpg',
        'variants': [('30','Khaki'),('32','Khaki'),('34','Khaki'),('36','Khaki')],
    },
    {
        'name': 'Striped Polo Shirt',
        'slug': 'striped-polo-shirt',
        'description': 'Classic striped polo shirt in premium pique cotton.',
        'price': 145.00, 'gender': 'men', 'brand': 'Club',
        'category_key': 'men', 'tags': 'polo, striped, casual, smart',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&auto=format&fit=crop&q=80',
        'image_name': 'striped-polo.jpg',
        'variants': [('S','Navy'),('M','Navy'),('L','White'),('XL','White')],
    },
    {
        'name': 'Denim Jacket',
        'slug': 'denim-jacket',
        'description': 'Classic denim jacket that never goes out of style.',
        'price': 255.00, 'gender': 'men', 'brand': 'Indigo',
        'category_key': 'men', 'tags': 'denim, jacket, casual, classic',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&auto=format&fit=crop&q=80',
        'image_name': 'denim-jacket.jpg',
        'variants': [('S','Blue'),('M','Blue'),('L','Blue'),('XL','Blue')],
    },
    {
        'name': 'Graphic Tee',
        'slug': 'graphic-tee-men',
        'description': 'Bold graphic tee in 100% combed cotton. Relaxed fit.',
        'price': 89.00, 'gender': 'men', 'brand': 'Urban',
        'category_key': 'men', 'tags': 'graphic, tee, casual, bold, cotton',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=600&auto=format&fit=crop&q=80',
        'image_name': 'graphic-tee.jpg',
        'variants': [('S','Black'),('M','Black'),('L','White'),('XL','White')],
    },
    {
        'name': 'Wool Blend Overcoat',
        'slug': 'wool-blend-overcoat',
        'description': 'Premium wool blend overcoat for cool weather. Sophisticated and warm.',
        'price': 620.00, 'gender': 'men', 'brand': 'Noir',
        'category_key': 'men', 'tags': 'coat, wool, winter, overcoat, formal',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&auto=format&fit=crop&q=80',
        'image_name': 'wool-overcoat.jpg',
        'variants': [('S','Camel'),('M','Camel'),('L','Grey'),('XL','Grey')],
    },
    {
        'name': 'Cargo Shorts',
        'slug': 'cargo-shorts-men',
        'description': 'Practical cargo shorts with multiple pockets. Perfect for outdoor activities.',
        'price': 120.00, 'gender': 'men', 'brand': 'Outfitters',
        'category_key': 'men', 'tags': 'cargo, shorts, outdoor, casual',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1591195853828-11db59a44f43?w=600&auto=format&fit=crop&q=80',
        'image_name': 'cargo-shorts.jpg',
        'variants': [('S','Olive'),('M','Olive'),('L','Khaki'),('XL','Khaki')],
    },
    {
        'name': 'Formal White Dress Shirt',
        'slug': 'formal-white-dress-shirt',
        'description': 'Crisp white dress shirt with spread collar. Essential for formal occasions.',
        'price': 165.00, 'gender': 'men', 'brand': 'Prestige',
        'category_key': 'men', 'tags': 'formal, shirt, white, dress, office',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=600&auto=format&fit=crop&q=80',
        'image_name': 'dress-shirt.jpg',
        'variants': [('S','White'),('M','White'),('L','White'),('XL','White')],
    },
    {
        'name': 'Slim Fit Suit',
        'slug': 'slim-fit-suit',
        'description': 'Complete slim fit two-piece suit. Perfect for weddings and formal events.',
        'price': 850.00, 'gender': 'men', 'brand': 'Prestige',
        'category_key': 'men', 'tags': 'suit, formal, slim, wedding, event',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=600&auto=format&fit=crop&q=80',
        'image_name': 'slim-suit.jpg',
        'variants': [('S','Navy'),('M','Navy'),('L','Charcoal'),('XL','Charcoal')],
    },
    {
        'name': 'Printed Ankara Shirt',
        'slug': 'printed-ankara-shirt',
        'description': 'Vibrant Ankara print shirt celebrating African heritage. Short sleeve.',
        'price': 195.00, 'gender': 'men', 'brand': 'Kente Co.',
        'category_key': 'men', 'tags': 'ankara, african, print, cultural, vibrant',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1589156280159-27698a70f29e?w=600&auto=format&fit=crop&q=80',
        'image_name': 'ankara-shirt.jpg',
        'variants': [('S','Multi'),('M','Multi'),('L','Multi'),('XL','Multi')],
    },
    {
        'name': 'Athletic Jogger Pants',
        'slug': 'athletic-jogger-pants',
        'description': 'Comfortable jogger pants in moisture-wicking fabric. Great for gym and leisure.',
        'price': 130.00, 'gender': 'men', 'brand': 'Active',
        'category_key': 'men', 'tags': 'jogger, athletic, sport, gym, casual',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=600&auto=format&fit=crop&q=80',
        'image_name': 'jogger-pants.jpg',
        'variants': [('S','Black'),('M','Black'),('L','Grey'),('XL','Grey')],
    },
    {
        'name': 'Cuban Collar Shirt',
        'slug': 'cuban-collar-shirt',
        'description': 'Relaxed Cuban collar shirt in breathable rayon. Great for summer.',
        'price': 155.00, 'gender': 'men', 'brand': 'Tropics',
        'category_key': 'men', 'tags': 'cuban, collar, summer, relaxed, rayon',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1604695573706-53170668f6a6?w=600&auto=format&fit=crop&q=80',
        'image_name': 'cuban-collar.jpg',
        'variants': [('S','Cream'),('M','Cream'),('L','Blue'),('XL','Blue')],
    },
    {
        'name': 'Classic Oxford Shoes',
        'slug': 'classic-oxford-shoes',
        'description': 'Genuine leather oxford shoes. Timeless design for formal occasions.',
        'price': 380.00, 'gender': 'men', 'brand': 'Heritage',
        'category_key': 'accessories', 'tags': 'shoes, oxford, leather, formal, classic',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1614252234498-9e2c5b1c35f3?w=600&auto=format&fit=crop&q=80',
        'image_name': 'oxford-shoes.jpg',
        'variants': [('40','Brown'),('41','Brown'),('42','Black'),('43','Black'),('44','Black')],
    },
    {
        'name': 'Oversized Hoodie',
        'slug': 'oversized-hoodie',
        'description': 'Cosy oversized hoodie in premium fleece. Perfect for cool evenings.',
        'price': 165.00, 'gender': 'unisex', 'brand': 'Cozy',
        'category_key': 'men', 'tags': 'hoodie, casual, oversized, cosy, fleece',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&auto=format&fit=crop&q=80',
        'image_name': 'hoodie.jpg',
        'variants': [('S','Grey'),('M','Grey'),('L','Black'),('XL','Black')],
    },
    {
        'name': 'Linen Trousers',
        'slug': 'linen-trousers-men',
        'description': 'Relaxed linen trousers in natural fabric. Ideal for warm weather.',
        'price': 185.00, 'gender': 'men', 'brand': 'Essentials',
        'category_key': 'men', 'tags': 'linen, trousers, summer, relaxed, natural',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&auto=format&fit=crop&q=80',
        'image_name': 'linen-trousers.jpg',
        'variants': [('S','Beige'),('M','Beige'),('L','White'),('XL','White')],
    },
    {
        'name': 'Bomber Jacket',
        'slug': 'bomber-jacket-men',
        'description': 'Classic bomber jacket with ribbed cuffs. Stylish and versatile.',
        'price': 295.00, 'gender': 'men', 'brand': 'Urban',
        'category_key': 'men', 'tags': 'bomber, jacket, casual, stylish',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&auto=format&fit=crop&q=80',
        'image_name': 'bomber-jacket.jpg',
        'variants': [('S','Olive'),('M','Olive'),('L','Black'),('XL','Black')],
    },
    {
        'name': 'Turtleneck Sweater',
        'slug': 'turtleneck-sweater-men',
        'description': 'Soft merino wool turtleneck sweater. Elegant and warm.',
        'price': 245.00, 'gender': 'men', 'brand': 'Wool & Co',
        'category_key': 'men', 'tags': 'turtleneck, sweater, wool, winter, elegant',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1580331451062-99ff652288d7?w=600&auto=format&fit=crop&q=80',
        'image_name': 'turtleneck.jpg',
        'variants': [('S','Cream'),('M','Cream'),('L','Black'),('XL','Navy')],
    },
    {
        'name': 'Relaxed Fit Shorts',
        'slug': 'relaxed-fit-shorts-men',
        'description': 'Comfortable relaxed fit shorts for casual wear and beach days.',
        'price': 99.00, 'gender': 'men', 'brand': 'Tropics',
        'category_key': 'men', 'tags': 'shorts, relaxed, casual, beach, summer',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=600&auto=format&fit=crop&q=80',
        'image_name': 'relaxed-shorts.jpg',
        'variants': [('S','Navy'),('M','Navy'),('L','Khaki'),('XL','Khaki')],
    },
    {
        'name': 'V-Neck T-Shirt Pack',
        'slug': 'v-neck-tshirt-pack',
        'description': 'Pack of 3 essential V-neck tees in premium cotton.',
        'price': 135.00, 'gender': 'men', 'brand': 'Essentials',
        'category_key': 'men', 'tags': 'vneck, tshirt, pack, essential, cotton',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&auto=format&fit=crop&q=80',
        'image_name': 'vneck-pack.jpg',
        'variants': [('S','Mixed'),('M','Mixed'),('L','Mixed'),('XL','Mixed')],
    },

    # ── WOMEN ─────────────────────────────────────────────────
    {
        'name': 'Floral Wrap Dress',
        'slug': 'floral-wrap-dress',
        'description': 'A beautiful floral wrap dress. Ideal for summer events and casual outings.',
        'price': 220.00, 'discount_price': 175.00, 'gender': 'women', 'brand': 'Bloom',
        'category_key': 'women', 'tags': 'floral, summer, dress, feminine',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1572804013427-4d7ca7268217?w=600&auto=format&fit=crop&q=80',
        'image_name': 'floral-dress.jpg',
        'variants': [('XS','Floral'),('S','Floral'),('M','Floral'),('L','Floral')],
    },
    {
        'name': 'High Waist Denim Jeans',
        'slug': 'high-waist-denim-jeans',
        'description': 'Classic high waist denim jeans. Versatile and comfortable for everyday wear.',
        'price': 195.00, 'gender': 'women', 'brand': 'Indigo',
        'category_key': 'women', 'tags': 'denim, jeans, casual, everyday, blue',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&auto=format&fit=crop&q=80',
        'image_name': 'denim-jeans.jpg',
        'variants': [('28','Blue'),('30','Blue'),('32','Blue'),('34','Blue')],
    },
    {
        'name': 'Silk Evening Blouse',
        'slug': 'silk-evening-blouse',
        'description': 'Luxurious silk blouse for evening occasions.',
        'price': 280.00, 'gender': 'women', 'brand': 'Luxe',
        'category_key': 'women', 'tags': 'silk, blouse, evening, elegant, luxury',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=600&auto=format&fit=crop&q=80',
        'image_name': 'silk-blouse.jpg',
        'variants': [('XS','Ivory'),('S','Ivory'),('M','Ivory'),('L','Ivory')],
    },
    {
        'name': 'Maxi Boho Dress',
        'slug': 'maxi-boho-dress',
        'description': 'Free-spirited boho maxi dress with intricate embroidery.',
        'price': 235.00, 'gender': 'women', 'brand': 'Bloom',
        'category_key': 'women', 'tags': 'boho, maxi, dress, embroidery, bohemian',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&auto=format&fit=crop&q=80',
        'image_name': 'maxi-boho.jpg',
        'variants': [('XS','Terracotta'),('S','Terracotta'),('M','Blue'),('L','Blue')],
    },
    {
        'name': 'Tailored Blazer Women',
        'slug': 'tailored-blazer-women',
        'description': 'Structured blazer for the modern professional woman.',
        'price': 395.00, 'gender': 'women', 'brand': 'Noir',
        'category_key': 'women', 'tags': 'blazer, formal, office, structured, professional',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1594938298603-c8148c4b0c4b?w=600&auto=format&fit=crop&q=80',
        'image_name': 'women-blazer.jpg',
        'variants': [('XS','Black'),('S','Black'),('M','Cream'),('L','Cream')],
    },
    {
        'name': 'Pleated Midi Skirt',
        'slug': 'pleated-midi-skirt',
        'description': 'Elegant pleated midi skirt in satin finish. Great for smart casual.',
        'price': 175.00, 'gender': 'women', 'brand': 'Grace',
        'category_key': 'women', 'tags': 'skirt, midi, pleated, satin, elegant',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&auto=format&fit=crop&q=80',
        'image_name': 'midi-skirt.jpg',
        'variants': [('XS','Blush'),('S','Blush'),('M','Black'),('L','Black')],
    },
    {
        'name': 'Cropped Knit Cardigan',
        'slug': 'cropped-knit-cardigan',
        'description': 'Trendy cropped knit cardigan. Perfect layering piece.',
        'price': 145.00, 'gender': 'women', 'brand': 'Cozy',
        'category_key': 'women', 'tags': 'knit, cardigan, cropped, layer, cosy',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&auto=format&fit=crop&q=80',
        'image_name': 'knit-cardigan.jpg',
        'variants': [('XS','Cream'),('S','Cream'),('M','Brown'),('L','Brown')],
    },
    {
        'name': 'Wide Leg Trousers',
        'slug': 'wide-leg-trousers-women',
        'description': 'Sophisticated wide leg trousers in flowing fabric.',
        'price': 210.00, 'gender': 'women', 'brand': 'Grace',
        'category_key': 'women', 'tags': 'wide leg, trousers, flowing, sophisticated',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80',
        'image_name': 'wide-leg-trousers.jpg',
        'variants': [('XS','Ivory'),('S','Ivory'),('M','Black'),('L','Black')],
    },
    {
        'name': 'Bodycon Mini Dress',
        'slug': 'bodycon-mini-dress',
        'description': 'Sleek bodycon mini dress for evening events.',
        'price': 199.00, 'gender': 'women', 'brand': 'Luxe',
        'category_key': 'women', 'tags': 'bodycon, mini, dress, evening, sleek',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80',
        'image_name': 'bodycon-dress.jpg',
        'variants': [('XS','Black'),('S','Black'),('M','Red'),('L','Red')],
    },
    {
        'name': 'Linen Co-ord Set',
        'slug': 'linen-coord-set',
        'description': 'Matching linen top and trouser co-ord set. Effortlessly chic.',
        'price': 285.00, 'gender': 'women', 'brand': 'Essentials',
        'category_key': 'women', 'tags': 'coord, linen, matching, chic, summer',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1594938298603-c8148c4b0c4b?w=600&auto=format&fit=crop&q=80',
        'image_name': 'linen-coord.jpg',
        'variants': [('XS','Sage'),('S','Sage'),('M','Sand'),('L','Sand')],
    },
    {
        'name': 'Off Shoulder Top',
        'slug': 'off-shoulder-top',
        'description': 'Romantic off shoulder top in soft cotton blend.',
        'price': 115.00, 'gender': 'women', 'brand': 'Bloom',
        'category_key': 'women', 'tags': 'off shoulder, top, romantic, cotton',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=600&auto=format&fit=crop&q=80',
        'image_name': 'off-shoulder.jpg',
        'variants': [('XS','White'),('S','White'),('M','Pink'),('L','Pink')],
    },
    {
        'name': 'Ankara Print Dress',
        'slug': 'ankara-print-dress',
        'description': 'Stunning Ankara print dress celebrating African fashion heritage.',
        'price': 245.00, 'gender': 'women', 'brand': 'Kente Co.',
        'category_key': 'women', 'tags': 'ankara, african, print, cultural, dress',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=600&auto=format&fit=crop&q=80',
        'image_name': 'ankara-dress.jpg',
        'variants': [('XS','Multi'),('S','Multi'),('M','Multi'),('L','Multi')],
    },
    {
        'name': 'Sports Bra Set',
        'slug': 'sports-bra-set',
        'description': 'High support sports bra and legging set. Perfect for the gym.',
        'price': 165.00, 'gender': 'women', 'brand': 'Active',
        'category_key': 'women', 'tags': 'sports, bra, gym, active, legging',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=600&auto=format&fit=crop&q=80',
        'image_name': 'sports-set.jpg',
        'variants': [('XS','Black'),('S','Black'),('M','Navy'),('L','Navy')],
    },
    {
        'name': 'Satin Slip Dress',
        'slug': 'satin-slip-dress',
        'description': 'Elegant satin slip dress. Wear alone or layered.',
        'price': 215.00, 'gender': 'women', 'brand': 'Luxe',
        'category_key': 'women', 'tags': 'satin, slip, dress, elegant, layering',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&auto=format&fit=crop&q=80',
        'image_name': 'satin-slip.jpg',
        'variants': [('XS','Champagne'),('S','Champagne'),('M','Black'),('L','Black')],
    },
    {
        'name': 'Puffer Jacket Women',
        'slug': 'puffer-jacket-women',
        'description': 'Warm and stylish puffer jacket for cooler days.',
        'price': 320.00, 'gender': 'women', 'brand': 'Nord',
        'category_key': 'women', 'tags': 'puffer, jacket, warm, winter, stylish',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1548624313-0396c75e4b1a?w=600&auto=format&fit=crop&q=80',
        'image_name': 'puffer-jacket.jpg',
        'variants': [('XS','Pink'),('S','Pink'),('M','Black'),('L','Black')],
    },
    {
        'name': 'Ruched Midi Dress',
        'slug': 'ruched-midi-dress',
        'description': 'Flattering ruched midi dress that hugs all the right curves.',
        'price': 225.00, 'gender': 'women', 'brand': 'Grace',
        'category_key': 'women', 'tags': 'ruched, midi, dress, flattering, curves',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&auto=format&fit=crop&q=80',
        'image_name': 'ruched-dress.jpg',
        'variants': [('XS','Burgundy'),('S','Burgundy'),('M','Forest'),('L','Forest')],
    },
    {
        'name': 'Trench Coat Women',
        'slug': 'trench-coat-women',
        'description': 'Classic belted trench coat. Timeless and sophisticated.',
        'price': 485.00, 'gender': 'women', 'brand': 'Noir',
        'category_key': 'women', 'tags': 'trench, coat, classic, belted, sophisticated',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1548126032-079a0fb0099d?w=600&auto=format&fit=crop&q=80',
        'image_name': 'trench-coat.jpg',
        'variants': [('XS','Camel'),('S','Camel'),('M','Black'),('L','Black')],
    },
    {
        'name': 'Ribbed Knit Dress',
        'slug': 'ribbed-knit-dress',
        'description': 'Cosy ribbed knit midi dress. Effortlessly stylish.',
        'price': 195.00, 'gender': 'women', 'brand': 'Cozy',
        'category_key': 'women', 'tags': 'ribbed, knit, dress, cosy, midi',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&auto=format&fit=crop&q=80',
        'image_name': 'ribbed-dress.jpg',
        'variants': [('XS','Cream'),('S','Cream'),('M','Brown'),('L','Brown')],
    },
    {
        'name': 'Button Down Shirt Dress',
        'slug': 'button-down-shirt-dress',
        'description': 'Relaxed shirt dress that transitions from day to night.',
        'price': 205.00, 'gender': 'women', 'brand': 'Essentials',
        'category_key': 'women', 'tags': 'shirt dress, button, relaxed, day to night',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600&auto=format&fit=crop&q=80',
        'image_name': 'shirt-dress.jpg',
        'variants': [('XS','Blue'),('S','Blue'),('M','White'),('L','White')],
    },
    {
        'name': 'Cut Out Swimsuit',
        'slug': 'cut-out-swimsuit',
        'description': 'Trendy cut-out one piece swimsuit. Beach ready.',
        'price': 155.00, 'gender': 'women', 'brand': 'Tropics',
        'category_key': 'women', 'tags': 'swimsuit, beach, cut out, one piece',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1570976447640-ac859f7b7c79?w=600&auto=format&fit=crop&q=80',
        'image_name': 'swimsuit.jpg',
        'variants': [('XS','Black'),('S','Black'),('M','Red'),('L','Red')],
    },

    # ── KIDS ──────────────────────────────────────────────────
    {
        'name': 'Kids Colourful Tee Pack',
        'slug': 'kids-colourful-tee-pack',
        'description': 'A fun pack of colourful tees for kids. Soft cotton and durable.',
        'price': 95.00, 'gender': 'kids', 'brand': 'Tiny',
        'category_key': 'kids', 'tags': 'kids, colourful, casual, cotton, tee',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kids-tee.jpg',
        'variants': [('3-4Y','Mixed'),('5-6Y','Mixed'),('7-8Y','Mixed')],
    },
    {
        'name': 'Kids Denim Overalls',
        'slug': 'kids-denim-overalls',
        'description': 'Adorable denim overalls for kids. Durable and comfortable.',
        'price': 135.00, 'gender': 'kids', 'brand': 'Tiny',
        'category_key': 'kids', 'tags': 'kids, denim, overalls, adorable',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kids-overalls.jpg',
        'variants': [('2-3Y','Blue'),('3-4Y','Blue'),('5-6Y','Blue'),('7-8Y','Blue')],
    },
    {
        'name': 'Kids Pyjama Set',
        'slug': 'kids-pyjama-set',
        'description': 'Soft cotton pyjama set with fun prints. Perfect for bedtime.',
        'price': 89.00, 'gender': 'kids', 'brand': 'Dreamz',
        'category_key': 'kids', 'tags': 'kids, pyjama, sleep, cotton, print',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kids-pyjama.jpg',
        'variants': [('2-3Y','Stars'),('3-4Y','Stars'),('5-6Y','Dinosaur'),('7-8Y','Dinosaur')],
    },
    {
        'name': 'Kids School Uniform Set',
        'slug': 'kids-school-uniform',
        'description': 'Complete school uniform set including shirt and trousers/skirt.',
        'price': 145.00, 'gender': 'kids', 'brand': 'Scholar',
        'category_key': 'kids', 'tags': 'kids, school, uniform, formal',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&auto=format&fit=crop&q=80',
        'image_name': 'school-uniform.jpg',
        'variants': [('4-5Y','White/Navy'),('5-6Y','White/Navy'),('7-8Y','White/Navy'),('9-10Y','White/Navy')],
    },
    {
        'name': 'Kids Ankara Outfit',
        'slug': 'kids-ankara-outfit',
        'description': 'Beautiful Ankara outfit for kids. Celebrate African fashion from a young age.',
        'price': 120.00, 'gender': 'kids', 'brand': 'Kente Co.',
        'category_key': 'kids', 'tags': 'kids, ankara, african, cultural, print',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kids-ankara.jpg',
        'variants': [('2-3Y','Multi'),('3-4Y','Multi'),('5-6Y','Multi'),('7-8Y','Multi')],
    },
    {
        'name': 'Kids Hoodie',
        'slug': 'kids-hoodie',
        'description': 'Soft fleece hoodie for kids. Warm and playful.',
        'price': 99.00, 'gender': 'kids', 'brand': 'Tiny',
        'category_key': 'kids', 'tags': 'kids, hoodie, warm, fleece, playful',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kids-hoodie.jpg',
        'variants': [('3-4Y','Red'),('5-6Y','Red'),('7-8Y','Blue'),('9-10Y','Blue')],
    },
    {
        'name': 'Kids Sneakers',
        'slug': 'kids-sneakers',
        'description': 'Comfortable and durable sneakers for active kids.',
        'price': 149.00, 'gender': 'kids', 'brand': 'Stride',
        'category_key': 'kids', 'tags': 'kids, sneakers, shoes, active, durable',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1555274175-6cbf6f3b137b?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kids-sneakers.jpg',
        'variants': [('28','White'),('29','White'),('30','Navy'),('31','Navy'),('32','Navy')],
    },
    {
        'name': 'Kids Summer Dress',
        'slug': 'kids-summer-dress',
        'description': 'Light and breezy summer dress for girls. Fun floral print.',
        'price': 105.00, 'gender': 'kids', 'brand': 'Bloom',
        'category_key': 'kids', 'tags': 'kids, dress, summer, floral, girls',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kids-dress.jpg',
        'variants': [('2-3Y','Floral'),('3-4Y','Floral'),('5-6Y','Floral'),('7-8Y','Floral')],
    },
    {
        'name': 'Kids Tracksuit',
        'slug': 'kids-tracksuit',
        'description': 'Sporty tracksuit set for active boys and girls.',
        'price': 125.00, 'gender': 'kids', 'brand': 'Active',
        'category_key': 'kids', 'tags': 'kids, tracksuit, sport, active',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kids-tracksuit.jpg',
        'variants': [('3-4Y','Black'),('5-6Y','Black'),('7-8Y','Navy'),('9-10Y','Navy')],
    },
    {
        'name': 'Kids Rain Jacket',
        'slug': 'kids-rain-jacket',
        'description': 'Waterproof rain jacket for kids. Keeps them dry and stylish.',
        'price': 159.00, 'gender': 'kids', 'brand': 'Nord',
        'category_key': 'kids', 'tags': 'kids, rain, jacket, waterproof, outdoor',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kids-rain.jpg',
        'variants': [('3-4Y','Yellow'),('5-6Y','Yellow'),('7-8Y','Red'),('9-10Y','Red')],
    },

    # ── ACCESSORIES ───────────────────────────────────────────
    {
        'name': 'Leather Crossbody Bag',
        'slug': 'leather-crossbody-bag',
        'description': 'Premium leather crossbody bag with multiple compartments.',
        'price': 310.00, 'gender': 'unisex', 'brand': 'Craft',
        'category_key': 'accessories', 'tags': 'bag, leather, crossbody, premium',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop&q=80',
        'image_name': 'leather-bag.jpg',
        'variants': [('One Size','Brown'),('One Size','Black')],
    },
    {
        'name': 'Canvas Tote Bag',
        'slug': 'canvas-tote-bag',
        'description': 'Large canvas tote bag. Eco-friendly and practical.',
        'price': 85.00, 'gender': 'unisex', 'brand': 'Craft',
        'category_key': 'accessories', 'tags': 'tote, canvas, bag, eco, practical',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=600&auto=format&fit=crop&q=80',
        'image_name': 'canvas-tote.jpg',
        'variants': [('One Size','Natural'),('One Size','Black')],
    },
    {
        'name': 'Silk Scarf',
        'slug': 'silk-scarf',
        'description': 'Luxurious silk scarf in vibrant prints. Wear it many ways.',
        'price': 120.00, 'gender': 'women', 'brand': 'Luxe',
        'category_key': 'accessories', 'tags': 'scarf, silk, luxury, print, versatile',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&auto=format&fit=crop&q=80',
        'image_name': 'silk-scarf.jpg',
        'variants': [('One Size','Floral'),('One Size','Abstract')],
    },
    {
        'name': 'Leather Belt',
        'slug': 'leather-belt',
        'description': 'Genuine leather belt with classic buckle. Essential wardrobe staple.',
        'price': 95.00, 'gender': 'unisex', 'brand': 'Heritage',
        'category_key': 'accessories', 'tags': 'belt, leather, classic, staple',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
        'image_name': 'leather-belt.jpg',
        'variants': [('S','Brown'),('M','Brown'),('L','Black'),('XL','Black')],
    },
    {
        'name': 'Straw Sun Hat',
        'slug': 'straw-sun-hat',
        'description': 'Classic straw sun hat for beach and outdoor occasions.',
        'price': 75.00, 'gender': 'unisex', 'brand': 'Tropics',
        'category_key': 'accessories', 'tags': 'hat, straw, sun, beach, outdoor',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1521369909029-2afed882baee?w=600&auto=format&fit=crop&q=80',
        'image_name': 'straw-hat.jpg',
        'variants': [('One Size','Natural')],
    },
    {
        'name': 'Gold Hoop Earrings',
        'slug': 'gold-hoop-earrings',
        'description': 'Classic gold hoop earrings in 18k gold plate. Timeless.',
        'price': 89.00, 'gender': 'women', 'brand': 'Luxe',
        'category_key': 'accessories', 'tags': 'earrings, gold, hoop, jewellery, classic',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80',
        'image_name': 'gold-hoops.jpg',
        'variants': [('Small','Gold'),('Large','Gold')],
    },
    {
        'name': 'Leather Wallet',
        'slug': 'leather-wallet',
        'description': 'Slim leather bifold wallet. Fits all essentials.',
        'price': 115.00, 'gender': 'men', 'brand': 'Heritage',
        'category_key': 'accessories', 'tags': 'wallet, leather, slim, bifold',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=600&auto=format&fit=crop&q=80',
        'image_name': 'leather-wallet.jpg',
        'variants': [('One Size','Brown'),('One Size','Black')],
    },
    {
        'name': 'Bucket Hat',
        'slug': 'bucket-hat',
        'description': 'Trendy bucket hat in cotton canvas. Street style essential.',
        'price': 65.00, 'gender': 'unisex', 'brand': 'Urban',
        'category_key': 'accessories', 'tags': 'bucket hat, street, casual, canvas',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=600&auto=format&fit=crop&q=80',
        'image_name': 'bucket-hat.jpg',
        'variants': [('One Size','Black'),('One Size','Beige'),('One Size','Camo')],
    },
    {
        'name': 'Beaded Bracelet Set',
        'slug': 'beaded-bracelet-set',
        'description': 'Handcrafted beaded bracelet set inspired by African tradition.',
        'price': 55.00, 'gender': 'unisex', 'brand': 'Kente Co.',
        'category_key': 'accessories', 'tags': 'bracelet, beaded, handcraft, african',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1573408301185-9519f94815f8?w=600&auto=format&fit=crop&q=80',
        'image_name': 'beaded-bracelet.jpg',
        'variants': [('One Size','Multi'),('One Size','Earth Tones')],
    },
    {
        'name': 'Aviator Sunglasses',
        'slug': 'aviator-sunglasses',
        'description': 'Classic aviator sunglasses with UV400 protection.',
        'price': 135.00, 'gender': 'unisex', 'brand': 'Vision',
        'category_key': 'accessories', 'tags': 'sunglasses, aviator, UV, classic',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1473496169904-658ba7574b0d?w=600&auto=format&fit=crop&q=80',
        'image_name': 'aviator-sunglasses.jpg',
        'variants': [('One Size','Gold/Brown'),('One Size','Silver/Grey')],
    },
    {
        'name': 'Mini Shoulder Bag',
        'slug': 'mini-shoulder-bag',
        'description': 'Compact mini shoulder bag. Perfect for evenings out.',
        'price': 175.00, 'gender': 'women', 'brand': 'Luxe',
        'category_key': 'accessories', 'tags': 'shoulder bag, mini, evening, compact',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80',
        'image_name': 'mini-shoulder-bag.jpg',
        'variants': [('One Size','Black'),('One Size','Tan'),('One Size','Red')],
    },
    {
        'name': 'Kente Kente Bow Tie',
        'slug': 'kente-bow-tie',
        'description': 'Handwoven Kente bow tie. A statement piece for formal events.',
        'price': 75.00, 'gender': 'men', 'brand': 'Kente Co.',
        'category_key': 'accessories', 'tags': 'bow tie, kente, formal, african, handwoven',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kente-bowtie.jpg',
        'variants': [('One Size','Multi')],
    },
    {
        'name': 'Gym Duffel Bag',
        'slug': 'gym-duffel-bag',
        'description': 'Spacious gym duffel bag with shoe compartment.',
        'price': 195.00, 'gender': 'unisex', 'brand': 'Active',
        'category_key': 'accessories', 'tags': 'gym, duffel, bag, sport, spacious',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
        'image_name': 'gym-bag.jpg',
        'variants': [('One Size','Black'),('One Size','Navy')],
    },
    {
        'name': 'Slip On Sneakers',
        'slug': 'slip-on-sneakers',
        'description': 'Easy slip-on sneakers in canvas. Casual and comfortable.',
        'price': 145.00, 'gender': 'unisex', 'brand': 'Stride',
        'category_key': 'accessories', 'tags': 'sneakers, slip on, casual, canvas',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80',
        'image_name': 'slip-on.jpg',
        'variants': [('38','White'),('39','White'),('40','Black'),('41','Black'),('42','Navy')],
    },
    {
        'name': 'Running Shoes',
        'slug': 'running-shoes',
        'description': 'Lightweight running shoes with cushioned sole.',
        'price': 285.00, 'gender': 'unisex', 'brand': 'Active',
        'category_key': 'accessories', 'tags': 'running, shoes, sport, lightweight',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
        'image_name': 'running-shoes.jpg',
        'variants': [('38','Black'),('39','Black'),('40','White'),('41','White'),('42','Blue'),('43','Blue')],
    },
    {
        'name': 'Sandals',
        'slug': 'flat-sandals',
        'description': 'Comfortable flat sandals in genuine leather.',
        'price': 165.00, 'gender': 'women', 'brand': 'Heritage',
        'category_key': 'accessories', 'tags': 'sandals, flat, leather, comfortable, summer',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop&q=80',
        'image_name': 'sandals.jpg',
        'variants': [('36','Tan'),('37','Tan'),('38','Tan'),('39','Black'),('40','Black')],
    },
    {
        'name': 'Watch — Classic',
        'slug': 'classic-watch',
        'description': 'Classic minimalist watch with leather strap. Timeless elegance.',
        'price': 350.00, 'gender': 'unisex', 'brand': 'Tempo',
        'category_key': 'accessories', 'tags': 'watch, classic, leather, minimalist, elegant',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
        'image_name': 'classic-watch.jpg',
        'variants': [('One Size','Gold/Brown'),('One Size','Silver/Black')],
    },
    {
        'name': 'Waist Bag',
        'slug': 'waist-bag',
        'description': 'Practical waist bag for hands-free convenience.',
        'price': 95.00, 'gender': 'unisex', 'brand': 'Urban',
        'category_key': 'accessories', 'tags': 'waist bag, fanny pack, casual, hands free',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop&q=80',
        'image_name': 'waist-bag.jpg',
        'variants': [('One Size','Black'),('One Size','Tan')],
    },

    # ── MORE MEN ──────────────────────────────────────────────────
    {
        'name': 'Henley Long Sleeve Shirt',
        'slug': 'henley-long-sleeve',
        'description': 'Classic Henley long sleeve in soft cotton. Relaxed and comfortable.',
        'price': 115.00, 'gender': 'men', 'brand': 'Essentials',
        'category_key': 'men', 'tags': 'henley, long sleeve, casual, cotton',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&auto=format&fit=crop&q=80',
        'image_name': 'henley-shirt.jpg',
        'variants': [('S','White'),('M','White'),('L','Grey'),('XL','Navy')],
    },
    {
        'name': 'Corduroy Trousers',
        'slug': 'corduroy-trousers-men',
        'description': 'Warm corduroy trousers in a relaxed fit. A cool-weather staple.',
        'price': 195.00, 'gender': 'men', 'brand': 'Heritage',
        'category_key': 'men', 'tags': 'corduroy, trousers, winter, warm',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=600&auto=format&fit=crop&q=80',
        'image_name': 'corduroy-trousers.jpg',
        'variants': [('30','Brown'),('32','Brown'),('34','Green'),('36','Green')],
    },
    {
        'name': 'Flannel Shirt',
        'slug': 'flannel-shirt-men',
        'description': 'Cosy flannel plaid shirt. Perfect for layering.',
        'price': 135.00, 'gender': 'men', 'brand': 'Outfitters',
        'category_key': 'men', 'tags': 'flannel, plaid, casual, layering',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1588359348347-9bc6cbbb689e?w=600&auto=format&fit=crop&q=80',
        'image_name': 'flannel-shirt.jpg',
        'variants': [('S','Red Plaid'),('M','Red Plaid'),('L','Blue Plaid'),('XL','Blue Plaid')],
    },
    {
        'name': 'Swim Shorts',
        'slug': 'swim-shorts-men',
        'description': 'Quick-dry swim shorts with elastic waistband. Beach ready.',
        'price': 105.00, 'gender': 'men', 'brand': 'Tropics',
        'category_key': 'men', 'tags': 'swim, shorts, beach, quick dry',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=600&auto=format&fit=crop&q=80',
        'image_name': 'swim-shorts.jpg',
        'variants': [('S','Blue'),('M','Blue'),('L','Green'),('XL','Green')],
    },
    {
        'name': 'Smart Casual Loafers',
        'slug': 'smart-casual-loafers',
        'description': 'Premium suede loafers. Effortlessly stylish for any occasion.',
        'price': 295.00, 'gender': 'men', 'brand': 'Heritage',
        'category_key': 'accessories', 'tags': 'loafers, suede, smart, casual, shoes',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1614252234498-9e2c5b1c35f3?w=600&auto=format&fit=crop&q=80',
        'image_name': 'suede-loafers.jpg',
        'variants': [('40','Tan'),('41','Tan'),('42','Navy'),('43','Navy'),('44','Black')],
    },
    {
        'name': 'Quarter Zip Pullover',
        'slug': 'quarter-zip-pullover',
        'description': 'Athletic quarter-zip pullover in moisture-wicking fabric.',
        'price': 155.00, 'gender': 'men', 'brand': 'Active',
        'category_key': 'men', 'tags': 'quarter zip, pullover, athletic, sport',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&auto=format&fit=crop&q=80',
        'image_name': 'quarter-zip.jpg',
        'variants': [('S','Navy'),('M','Navy'),('L','Black'),('XL','Black')],
    },
    {
        'name': 'Kente Print Shorts',
        'slug': 'kente-print-shorts',
        'description': 'Bold Kente-inspired print shorts. Celebrate African heritage in style.',
        'price': 115.00, 'gender': 'men', 'brand': 'Kente Co.',
        'category_key': 'men', 'tags': 'kente, shorts, african, print, bold',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kente-shorts.jpg',
        'variants': [('S','Multi'),('M','Multi'),('L','Multi'),('XL','Multi')],
    },
    {
        'name': 'Utility Jacket',
        'slug': 'utility-jacket-men',
        'description': 'Practical utility jacket with multiple pockets.',
        'price': 275.00, 'gender': 'men', 'brand': 'Outfitters',
        'category_key': 'men', 'tags': 'utility, jacket, practical, pockets',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&auto=format&fit=crop&q=80',
        'image_name': 'utility-jacket.jpg',
        'variants': [('S','Khaki'),('M','Khaki'),('L','Black'),('XL','Black')],
    },
    {
        'name': 'Merino Crewneck Sweater',
        'slug': 'merino-crewneck-sweater',
        'description': 'Soft merino wool crewneck sweater. Lightweight and warm.',
        'price': 265.00, 'gender': 'men', 'brand': 'Wool & Co',
        'category_key': 'men', 'tags': 'merino, wool, crewneck, sweater, warm',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1580331451062-99ff652288d7?w=600&auto=format&fit=crop&q=80',
        'image_name': 'merino-sweater.jpg',
        'variants': [('S','Oatmeal'),('M','Oatmeal'),('L','Navy'),('XL','Navy')],
    },
    {
        'name': 'Chelsea Boots',
        'slug': 'chelsea-boots-men',
        'description': 'Classic leather Chelsea boots. A timeless wardrobe essential.',
        'price': 420.00, 'gender': 'men', 'brand': 'Heritage',
        'category_key': 'accessories', 'tags': 'chelsea, boots, leather, classic',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80',
        'image_name': 'chelsea-boots.jpg',
        'variants': [('40','Black'),('41','Black'),('42','Brown'),('43','Brown'),('44','Tan')],
    },
    {
        'name': 'Relaxed Linen Shirt',
        'slug': 'relaxed-linen-shirt-men',
        'description': 'Loose fitting linen shirt in natural earthy tones.',
        'price': 145.00, 'gender': 'men', 'brand': 'Essentials',
        'category_key': 'men', 'tags': 'linen, shirt, relaxed, earthy, summer',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&auto=format&fit=crop&q=80',
        'image_name': 'linen-shirt-2.jpg',
        'variants': [('S','Sand'),('M','Sand'),('L','Sage'),('XL','Sage')],
    },
    {
        'name': 'Track Jacket',
        'slug': 'track-jacket-men',
        'description': 'Retro-inspired track jacket. Sporty and stylish.',
        'price': 185.00, 'gender': 'men', 'brand': 'Active',
        'category_key': 'men', 'tags': 'track, jacket, retro, sport',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&auto=format&fit=crop&q=80',
        'image_name': 'track-jacket.jpg',
        'variants': [('S','Black/White'),('M','Black/White'),('L','Navy/Red'),('XL','Navy/Red')],
    },
    {
        'name': 'Printed Boardshorts',
        'slug': 'printed-boardshorts',
        'description': 'Fun printed boardshorts for beach days. Quick-dry fabric.',
        'price': 95.00, 'gender': 'men', 'brand': 'Tropics',
        'category_key': 'men', 'tags': 'boardshorts, beach, print, quick dry',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=600&auto=format&fit=crop&q=80',
        'image_name': 'boardshorts.jpg',
        'variants': [('S','Tropical'),('M','Tropical'),('L','Stripe'),('XL','Stripe')],
    },
    {
        'name': 'Formal Waistcoat',
        'slug': 'formal-waistcoat',
        'description': 'Classic formal waistcoat. Pairs perfectly with our suit range.',
        'price': 195.00, 'gender': 'men', 'brand': 'Prestige',
        'category_key': 'men', 'tags': 'waistcoat, formal, suit, classic',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=600&auto=format&fit=crop&q=80',
        'image_name': 'waistcoat.jpg',
        'variants': [('S','Charcoal'),('M','Charcoal'),('L','Navy'),('XL','Navy')],
    },
    {
        'name': 'Knitted Cardigan Men',
        'slug': 'knitted-cardigan-men',
        'description': 'Button-up knitted cardigan. Smart casual at its best.',
        'price': 215.00, 'gender': 'men', 'brand': 'Wool & Co',
        'category_key': 'men', 'tags': 'cardigan, knit, smart, casual, button',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&auto=format&fit=crop&q=80',
        'image_name': 'mens-cardigan.jpg',
        'variants': [('S','Grey'),('M','Grey'),('L','Brown'),('XL','Brown')],
    },
    {
        'name': 'Athletic Shorts',
        'slug': 'athletic-shorts-men',
        'description': 'Lightweight athletic shorts for training and gym sessions.',
        'price': 85.00, 'gender': 'men', 'brand': 'Active',
        'category_key': 'men', 'tags': 'athletic, shorts, gym, training, sport',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=600&auto=format&fit=crop&q=80',
        'image_name': 'athletic-shorts.jpg',
        'variants': [('S','Black'),('M','Black'),('L','Navy'),('XL','Grey')],
    },
    {
        'name': 'Longline T-Shirt',
        'slug': 'longline-tshirt',
        'description': 'Extended length longline tee with curved hem. Streetwear staple.',
        'price': 95.00, 'gender': 'men', 'brand': 'Urban',
        'category_key': 'men', 'tags': 'longline, tshirt, streetwear, curved hem',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=600&auto=format&fit=crop&q=80',
        'image_name': 'longline-tee.jpg',
        'variants': [('S','White'),('M','Black'),('L','Grey'),('XL','White')],
    },
    {
        'name': 'Tweed Sport Coat',
        'slug': 'tweed-sport-coat',
        'description': 'Classic British-inspired tweed sport coat. Timeless heritage style.',
        'price': 520.00, 'gender': 'men', 'brand': 'Heritage',
        'category_key': 'men', 'tags': 'tweed, sport coat, heritage, classic, formal',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
        'image_name': 'tweed-coat.jpg',
        'variants': [('S','Brown'),('M','Brown'),('L','Grey'),('XL','Grey')],
    },
    {
        'name': 'Compression Tights',
        'slug': 'compression-tights-men',
        'description': 'High performance compression tights for training.',
        'price': 115.00, 'gender': 'men', 'brand': 'Active',
        'category_key': 'men', 'tags': 'compression, tights, training, performance',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=600&auto=format&fit=crop&q=80',
        'image_name': 'compression-tights.jpg',
        'variants': [('S','Black'),('M','Black'),('L','Navy'),('XL','Navy')],
    },
    {
        'name': 'Dad Hat',
        'slug': 'dad-hat',
        'description': 'Relaxed fit cotton dad hat. A streetwear classic.',
        'price': 55.00, 'gender': 'men', 'brand': 'Urban',
        'category_key': 'accessories', 'tags': 'dad hat, cap, streetwear, casual',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=600&auto=format&fit=crop&q=80',
        'image_name': 'dad-hat.jpg',
        'variants': [('One Size','Black'),('One Size','White'),('One Size','Olive')],
    },

    # ── MORE WOMEN ─────────────────────────────────────────────
    {
        'name': 'Blazer Dress',
        'slug': 'blazer-dress-women',
        'description': 'Power dressing at its finest. Blazer dress with belt.',
        'price': 335.00, 'gender': 'women', 'brand': 'Noir',
        'category_key': 'women', 'tags': 'blazer, dress, power, belt, formal',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80',
        'image_name': 'blazer-dress.jpg',
        'variants': [('XS','Black'),('S','Black'),('M','Camel'),('L','Camel')],
    },
    {
        'name': 'Crochet Cover Up',
        'slug': 'crochet-cover-up',
        'description': 'Bohemian crochet beach cover up. Perfect over swimwear.',
        'price': 135.00, 'gender': 'women', 'brand': 'Tropics',
        'category_key': 'women', 'tags': 'crochet, beach, cover up, bohemian',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1570976447640-ac859f7b7c79?w=600&auto=format&fit=crop&q=80',
        'image_name': 'crochet-coverup.jpg',
        'variants': [('One Size','White'),('One Size','Cream')],
    },
    {
        'name': 'Leather Trousers',
        'slug': 'leather-trousers-women',
        'description': 'Edgy faux leather trousers. Rock your look.',
        'price': 265.00, 'gender': 'women', 'brand': 'Urban',
        'category_key': 'women', 'tags': 'leather, trousers, edgy, faux, bold',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80',
        'image_name': 'leather-trousers.jpg',
        'variants': [('XS','Black'),('S','Black'),('M','Black'),('L','Black')],
    },
    {
        'name': 'Oversized Denim Shirt',
        'slug': 'oversized-denim-shirt-women',
        'description': 'Relaxed oversized denim shirt. Wear as a top or layer.',
        'price': 155.00, 'gender': 'women', 'brand': 'Indigo',
        'category_key': 'women', 'tags': 'denim, shirt, oversized, layer, casual',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=600&auto=format&fit=crop&q=80',
        'image_name': 'oversized-denim.jpg',
        'variants': [('XS','Blue'),('S','Blue'),('M','Blue'),('L','Blue')],
    },
    {
        'name': 'Jogger Set Women',
        'slug': 'jogger-set-women',
        'description': 'Matching hoodie and jogger set. Loungewear at its finest.',
        'price': 195.00, 'gender': 'women', 'brand': 'Cozy',
        'category_key': 'women', 'tags': 'jogger, set, loungewear, matching, cosy',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=600&auto=format&fit=crop&q=80',
        'image_name': 'jogger-set.jpg',
        'variants': [('XS','Sage'),('S','Sage'),('M','Pink'),('L','Pink')],
    },
    {
        'name': 'Strappy Heels',
        'slug': 'strappy-heels',
        'description': 'Elegant strappy heels for evenings and special occasions.',
        'price': 255.00, 'gender': 'women', 'brand': 'Grace',
        'category_key': 'accessories', 'tags': 'heels, strappy, elegant, evening',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop&q=80',
        'image_name': 'strappy-heels.jpg',
        'variants': [('36','Gold'),('37','Gold'),('38','Black'),('39','Black'),('40','Nude')],
    },
    {
        'name': 'Wrap Jumpsuit',
        'slug': 'wrap-jumpsuit',
        'description': 'Elegant wrap jumpsuit with tie waist. Great for events.',
        'price': 245.00, 'gender': 'women', 'brand': 'Grace',
        'category_key': 'women', 'tags': 'jumpsuit, wrap, elegant, tie waist',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=600&auto=format&fit=crop&q=80',
        'image_name': 'wrap-jumpsuit.jpg',
        'variants': [('XS','Emerald'),('S','Emerald'),('M','Black'),('L','Black')],
    },
    {
        'name': 'Mini Shorts Women',
        'slug': 'mini-shorts-women',
        'description': 'High-waisted mini shorts. Perfect for summer.',
        'price': 95.00, 'gender': 'women', 'brand': 'Bloom',
        'category_key': 'women', 'tags': 'shorts, mini, high waist, summer',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&auto=format&fit=crop&q=80',
        'image_name': 'mini-shorts.jpg',
        'variants': [('XS','Denim'),('S','Denim'),('M','Black'),('L','Black')],
    },
    {
        'name': 'Chunky Knit Sweater',
        'slug': 'chunky-knit-sweater-women',
        'description': 'Cosy chunky knit oversized sweater. A winter must-have.',
        'price': 225.00, 'gender': 'women', 'brand': 'Cozy',
        'category_key': 'women', 'tags': 'chunky, knit, sweater, oversized, winter',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&auto=format&fit=crop&q=80',
        'image_name': 'chunky-knit.jpg',
        'variants': [('XS','Cream'),('S','Cream'),('M','Caramel'),('L','Caramel')],
    },
    {
        'name': 'Asymmetric Hem Dress',
        'slug': 'asymmetric-hem-dress',
        'description': 'Fashion-forward asymmetric hem midi dress.',
        'price': 235.00, 'gender': 'women', 'brand': 'Noir',
        'category_key': 'women', 'tags': 'asymmetric, hem, dress, midi, fashion',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=600&auto=format&fit=crop&q=80',
        'image_name': 'asymmetric-dress.jpg',
        'variants': [('XS','Black'),('S','Black'),('M','White'),('L','White')],
    },
    {
        'name': 'Mesh Panel Leggings',
        'slug': 'mesh-panel-leggings',
        'description': 'High waist leggings with mesh panel detailing. Gym to street.',
        'price': 125.00, 'gender': 'women', 'brand': 'Active',
        'category_key': 'women', 'tags': 'leggings, mesh, gym, high waist, sport',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=600&auto=format&fit=crop&q=80',
        'image_name': 'mesh-leggings.jpg',
        'variants': [('XS','Black'),('S','Black'),('M','Navy'),('L','Navy')],
    },
    {
        'name': 'Flare Jeans',
        'slug': 'flare-jeans-women',
        'description': '70s inspired flare jeans. Retro meets modern.',
        'price': 205.00, 'gender': 'women', 'brand': 'Indigo',
        'category_key': 'women', 'tags': 'flare, jeans, retro, denim, 70s',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=600&auto=format&fit=crop&q=80',
        'image_name': 'flare-jeans.jpg',
        'variants': [('26','Blue'),('28','Blue'),('30','Black'),('32','Black')],
    },
    {
        'name': 'Embroidered Kurta',
        'slug': 'embroidered-kurta',
        'description': 'Beautifully embroidered kurta-style top. Elegant cultural wear.',
        'price': 175.00, 'gender': 'women', 'brand': 'Kente Co.',
        'category_key': 'women', 'tags': 'embroidered, kurta, cultural, elegant',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=600&auto=format&fit=crop&q=80',
        'image_name': 'embroidered-kurta.jpg',
        'variants': [('XS','White'),('S','White'),('M','Blue'),('L','Blue')],
    },
    {
        'name': 'Cargo Pants Women',
        'slug': 'cargo-pants-women',
        'description': 'Relaxed cargo pants with lots of pockets. Utility meets fashion.',
        'price': 185.00, 'gender': 'women', 'brand': 'Urban',
        'category_key': 'women', 'tags': 'cargo, pants, utility, pockets, fashion',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=600&auto=format&fit=crop&q=80',
        'image_name': 'cargo-pants-women.jpg',
        'variants': [('XS','Khaki'),('S','Khaki'),('M','Black'),('L','Black')],
    },
    {
        'name': 'Cowl Neck Dress',
        'slug': 'cowl-neck-dress',
        'description': 'Draped cowl neck dress in silky fabric. Sophisticated and sensual.',
        'price': 255.00, 'gender': 'women', 'brand': 'Luxe',
        'category_key': 'women', 'tags': 'cowl neck, dress, draped, silky, elegant',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&auto=format&fit=crop&q=80',
        'image_name': 'cowl-dress.jpg',
        'variants': [('XS','Cream'),('S','Cream'),('M','Blush'),('L','Blush')],
    },
    {
        'name': 'Chelsea Boots Women',
        'slug': 'chelsea-boots-women',
        'description': 'Classic leather Chelsea boots for women. Timeless style.',
        'price': 385.00, 'gender': 'women', 'brand': 'Heritage',
        'category_key': 'accessories', 'tags': 'chelsea, boots, leather, classic, women',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop&q=80',
        'image_name': 'women-chelsea-boots.jpg',
        'variants': [('36','Black'),('37','Black'),('38','Tan'),('39','Tan'),('40','Brown')],
    },
    {
        'name': 'Longline Cardigan',
        'slug': 'longline-cardigan-women',
        'description': 'Duster-length longline cardigan. The ultimate layering piece.',
        'price': 195.00, 'gender': 'women', 'brand': 'Cozy',
        'category_key': 'women', 'tags': 'longline, cardigan, duster, layer',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=600&auto=format&fit=crop&q=80',
        'image_name': 'longline-cardigan.jpg',
        'variants': [('XS','Cream'),('S','Cream'),('M','Black'),('L','Black')],
    },
    {
        'name': 'Biker Shorts',
        'slug': 'biker-shorts-women',
        'description': 'High waist biker shorts. Workout or streetwear.',
        'price': 89.00, 'gender': 'women', 'brand': 'Active',
        'category_key': 'women', 'tags': 'biker, shorts, high waist, gym, street',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?w=600&auto=format&fit=crop&q=80',
        'image_name': 'biker-shorts.jpg',
        'variants': [('XS','Black'),('S','Black'),('M','Olive'),('L','Olive')],
    },
    {
        'name': 'Crop Blazer',
        'slug': 'crop-blazer-women',
        'description': 'Tailored cropped blazer. Perfect over high-waisted bottoms.',
        'price': 285.00, 'gender': 'women', 'brand': 'Noir',
        'category_key': 'women', 'tags': 'blazer, crop, tailored, smart',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1594938298603-c8148c4b0c4b?w=600&auto=format&fit=crop&q=80',
        'image_name': 'crop-blazer.jpg',
        'variants': [('XS','White'),('S','White'),('M','Black'),('L','Black')],
    },
    {
        'name': 'Strapless Bandeau Top',
        'slug': 'strapless-bandeau-top',
        'description': 'Seamless strapless bandeau top. Pairs with everything.',
        'price': 65.00, 'gender': 'women', 'brand': 'Essentials',
        'category_key': 'women', 'tags': 'bandeau, strapless, top, seamless',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=600&auto=format&fit=crop&q=80',
        'image_name': 'bandeau-top.jpg',
        'variants': [('XS','Black'),('S','Black'),('M','White'),('L','White')],
    },

    # ── MORE KIDS ─────────────────────────────────────────────
    {
        'name': 'Kids Polo Shirt',
        'slug': 'kids-polo-shirt',
        'description': 'Smart polo shirt for boys and girls. Easy care cotton.',
        'price': 75.00, 'gender': 'kids', 'brand': 'Scholar',
        'category_key': 'kids', 'tags': 'kids, polo, smart, cotton, easy care',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kids-polo.jpg',
        'variants': [('3-4Y','White'),('5-6Y','White'),('7-8Y','Navy'),('9-10Y','Navy')],
    },
    {
        'name': 'Kids Swim Set',
        'slug': 'kids-swim-set',
        'description': 'Fun printed swim shorts and rash guard set for kids.',
        'price': 110.00, 'gender': 'kids', 'brand': 'Tropics',
        'category_key': 'kids', 'tags': 'kids, swim, beach, rashguard, set',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kids-swimset.jpg',
        'variants': [('3-4Y','Blue'),('5-6Y','Blue'),('7-8Y','Green'),('9-10Y','Green')],
    },
    {
        'name': 'Girls Party Dress',
        'slug': 'girls-party-dress',
        'description': 'Sparkly party dress for girls. Perfect for birthdays and special occasions.',
        'price': 135.00, 'gender': 'kids', 'brand': 'Bloom',
        'category_key': 'kids', 'tags': 'kids, girls, party, dress, sparkly',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=600&auto=format&fit=crop&q=80',
        'image_name': 'girls-party-dress.jpg',
        'variants': [('2-3Y','Pink'),('3-4Y','Pink'),('5-6Y','Gold'),('7-8Y','Gold')],
    },
    {
        'name': 'Boys Suit Set',
        'slug': 'boys-suit-set',
        'description': 'Smart suit set for boys. Perfect for weddings and formal events.',
        'price': 185.00, 'gender': 'kids', 'brand': 'Scholar',
        'category_key': 'kids', 'tags': 'kids, boys, suit, formal, wedding',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&auto=format&fit=crop&q=80',
        'image_name': 'boys-suit.jpg',
        'variants': [('3-4Y','Navy'),('5-6Y','Navy'),('7-8Y','Grey'),('9-10Y','Grey')],
    },
    {
        'name': 'Kids Winter Coat',
        'slug': 'kids-winter-coat',
        'description': 'Warm padded winter coat for kids. Keeps them cosy all winter.',
        'price': 195.00, 'gender': 'kids', 'brand': 'Nord',
        'category_key': 'kids', 'tags': 'kids, coat, winter, warm, padded',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kids-winter-coat.jpg',
        'variants': [('3-4Y','Red'),('5-6Y','Red'),('7-8Y','Blue'),('9-10Y','Blue')],
    },
    {
        'name': 'Kids Graphic Tee',
        'slug': 'kids-graphic-tee',
        'description': 'Fun graphic tee for kids with bold prints and bright colours.',
        'price': 65.00, 'gender': 'kids', 'brand': 'Tiny',
        'category_key': 'kids', 'tags': 'kids, graphic, tee, fun, colourful',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kids-graphic-tee.jpg',
        'variants': [('3-4Y','Multi'),('5-6Y','Multi'),('7-8Y','Multi'),('9-10Y','Multi')],
    },
    {
        'name': 'Kids Sandals',
        'slug': 'kids-sandals',
        'description': 'Comfortable velcro sandals for kids. Easy to put on and take off.',
        'price': 85.00, 'gender': 'kids', 'brand': 'Stride',
        'category_key': 'kids', 'tags': 'kids, sandals, velcro, comfortable',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1555274175-6cbf6f3b137b?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kids-sandals.jpg',
        'variants': [('25','Pink'),('26','Pink'),('27','Blue'),('28','Blue'),('29','White')],
    },
    {
        'name': 'Kids Denim Shorts',
        'slug': 'kids-denim-shorts',
        'description': 'Classic denim shorts for kids. Great for play.',
        'price': 79.00, 'gender': 'kids', 'brand': 'Tiny',
        'category_key': 'kids', 'tags': 'kids, denim, shorts, casual, play',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1471286174890-9c112ffca5b4?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kids-denim-shorts.jpg',
        'variants': [('3-4Y','Blue'),('5-6Y','Blue'),('7-8Y','Blue'),('9-10Y','Blue')],
    },

    # ── MORE ACCESSORIES ──────────────────────────────────────
    {
        'name': 'Leather Backpack',
        'slug': 'leather-backpack',
        'description': 'Premium leather backpack. Stylish and functional.',
        'price': 385.00, 'gender': 'unisex', 'brand': 'Craft',
        'category_key': 'accessories', 'tags': 'backpack, leather, premium, functional',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&auto=format&fit=crop&q=80',
        'image_name': 'leather-backpack.jpg',
        'variants': [('One Size','Brown'),('One Size','Black')],
    },
    {
        'name': 'Ankle Boots Women',
        'slug': 'ankle-boots-women',
        'description': 'Versatile leather ankle boots. From office to weekend.',
        'price': 315.00, 'gender': 'women', 'brand': 'Heritage',
        'category_key': 'accessories', 'tags': 'ankle, boots, leather, versatile',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop&q=80',
        'image_name': 'ankle-boots.jpg',
        'variants': [('36','Black'),('37','Black'),('38','Brown'),('39','Brown'),('40','Tan')],
    },
    {
        'name': 'Statement Necklace',
        'slug': 'statement-necklace',
        'description': 'Bold African-inspired statement necklace. Elevates any outfit.',
        'price': 95.00, 'gender': 'women', 'brand': 'Kente Co.',
        'category_key': 'accessories', 'tags': 'necklace, statement, african, bold, jewellery',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80',
        'image_name': 'statement-necklace.jpg',
        'variants': [('One Size','Gold'),('One Size','Silver')],
    },
    {
        'name': 'Polarised Sunglasses',
        'slug': 'polarised-sunglasses',
        'description': 'Premium polarised sunglasses for ultimate UV protection.',
        'price': 185.00, 'gender': 'unisex', 'brand': 'Vision',
        'category_key': 'accessories', 'tags': 'sunglasses, polarised, UV, premium',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1473496169904-658ba7574b0d?w=600&auto=format&fit=crop&q=80',
        'image_name': 'polarised-sunglasses.jpg',
        'variants': [('One Size','Black'),('One Size','Tortoise')],
    },
    {
        'name': 'Laptop Bag',
        'slug': 'laptop-bag',
        'description': 'Sleek laptop bag for the professional. Fits up to 15 inch laptop.',
        'price': 225.00, 'gender': 'unisex', 'brand': 'Craft',
        'category_key': 'accessories', 'tags': 'laptop, bag, professional, work',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
        'image_name': 'laptop-bag.jpg',
        'variants': [('One Size','Black'),('One Size','Grey')],
    },
    {
        'name': 'Smart Watch',
        'slug': 'smart-watch',
        'description': 'Feature-rich smartwatch with health tracking. Style meets technology.',
        'price': 450.00, 'gender': 'unisex', 'brand': 'Tempo',
        'category_key': 'accessories', 'tags': 'smartwatch, tech, health, style',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
        'image_name': 'smart-watch.jpg',
        'variants': [('One Size','Black'),('One Size','Silver')],
    },
    {
        'name': 'Cufflinks Set',
        'slug': 'cufflinks-set',
        'description': 'Premium gold cufflinks set. The finishing touch for formal occasions.',
        'price': 75.00, 'gender': 'men', 'brand': 'Prestige',
        'category_key': 'accessories', 'tags': 'cufflinks, formal, gold, men, jewellery',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&auto=format&fit=crop&q=80',
        'image_name': 'cufflinks.jpg',
        'variants': [('One Size','Gold'),('One Size','Silver')],
    },
    {
        'name': 'Knitted Beanie',
        'slug': 'knitted-beanie',
        'description': 'Soft ribbed knit beanie. Warm and stylish for cooler days.',
        'price': 45.00, 'gender': 'unisex', 'brand': 'Cozy',
        'category_key': 'accessories', 'tags': 'beanie, knit, warm, winter, hat',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=600&auto=format&fit=crop&q=80',
        'image_name': 'knitted-beanie.jpg',
        'variants': [('One Size','Black'),('One Size','Grey'),('One Size','Cream')],
    },
    {
        'name': 'Chain Bracelet',
        'slug': 'chain-bracelet',
        'description': 'Minimalist chain bracelet in sterling silver. Understated elegance.',
        'price': 65.00, 'gender': 'unisex', 'brand': 'Luxe',
        'category_key': 'accessories', 'tags': 'bracelet, chain, silver, minimalist',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1573408301185-9519f94815f8?w=600&auto=format&fit=crop&q=80',
        'image_name': 'chain-bracelet.jpg',
        'variants': [('One Size','Silver'),('One Size','Gold')],
    },
    {
        'name': 'High Top Sneakers',
        'slug': 'high-top-sneakers',
        'description': 'Classic canvas high-top sneakers. A streetwear icon.',
        'price': 195.00, 'gender': 'unisex', 'brand': 'Stride',
        'category_key': 'accessories', 'tags': 'sneakers, high top, canvas, streetwear',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80',
        'image_name': 'high-top-sneakers.jpg',
        'variants': [('38','White'),('39','White'),('40','Black'),('41','Black'),('42','Red')],
    },
    {
        'name': 'Silk Pocket Square',
        'slug': 'silk-pocket-square',
        'description': 'Luxurious silk pocket square. The perfect formal accessory.',
        'price': 45.00, 'gender': 'men', 'brand': 'Prestige',
        'category_key': 'accessories', 'tags': 'pocket square, silk, formal, men',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&auto=format&fit=crop&q=80',
        'image_name': 'pocket-square.jpg',
        'variants': [('One Size','White'),('One Size','Navy'),('One Size','Burgundy')],
    },
    {
        'name': 'Raffia Basket Bag',
        'slug': 'raffia-basket-bag',
        'description': 'Handwoven raffia basket bag. Artisanal and sustainable.',
        'price': 145.00, 'gender': 'women', 'brand': 'Craft',
        'category_key': 'accessories', 'tags': 'raffia, basket, bag, handwoven, artisanal',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&auto=format&fit=crop&q=80',
        'image_name': 'raffia-bag.jpg',
        'variants': [('One Size','Natural'),('One Size','Natural/Black')],
    },
    {
        'name': 'Tie Collection',
        'slug': 'tie-collection',
        'description': 'Set of 3 premium silk ties. Essential for the formal wardrobe.',
        'price': 135.00, 'gender': 'men', 'brand': 'Prestige',
        'category_key': 'accessories', 'tags': 'tie, silk, formal, set, men',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&auto=format&fit=crop&q=80',
        'image_name': 'tie-set.jpg',
        'variants': [('One Size','Mixed')],
    },
    {
        'name': 'Platform Sneakers',
        'slug': 'platform-sneakers',
        'description': 'Chunky platform sneakers. Make a bold fashion statement.',
        'price': 235.00, 'gender': 'women', 'brand': 'Urban',
        'category_key': 'accessories', 'tags': 'platform, sneakers, chunky, bold',
        'is_featured': False,
        'image_url': 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80',
        'image_name': 'platform-sneakers.jpg',
        'variants': [('36','White'),('37','White'),('38','Black'),('39','Black'),('40','Pink')],
    },
    {
        'name': 'Kofi Hat',
        'slug': 'kofi-hat',
        'description': 'Traditional Ghanaian Kofi hat in kente fabric. Cultural pride.',
        'price': 85.00, 'gender': 'men', 'brand': 'Kente Co.',
        'category_key': 'accessories', 'tags': 'kofi, hat, ghanaian, kente, cultural',
        'is_featured': True,
        'image_url': 'https://images.unsplash.com/photo-1521369909029-2afed882baee?w=600&auto=format&fit=crop&q=80',
        'image_name': 'kofi-hat.jpg',
        'variants': [('S','Multi'),('M','Multi'),('L','Multi')],
    },
]

created = 0
for p in products_data:
    if Product.objects.filter(slug=p['slug']).exists():
        print(f'Skipping {p["name"]} — already exists')
        continue

    variants_data = p.pop('variants')
    image_url = p.pop('image_url')
    image_name = p.pop('image_name')
    category_key = p.pop('category_key')
    discount_price = p.pop('discount_price', None)

    product = Product.objects.create(
        created_by=admin,
        category=cats[category_key],
        discount_price=discount_price,
        **p
    )

    for size, color in variants_data:
        ProductVariant.objects.create(
            product=product, size=size, color=color, stock=25
        )

    tmp = download_image(image_url, image_name)
    if tmp:
        with open(tmp, 'rb') as f:
            pi = ProductImage(product=product, is_primary=True, order=0)
            pi.image.save(image_name, File(f), save=True)
        os.unlink(tmp)
        print(f'✓ {product.name}')
    else:
        print(f'✓ {product.name} (no image)')

    created += 1

print(f'\nDone — {created} products created.')