# Generated by Django 6.0.4 on 2026-09-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delivery_pin_paystack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack (MoMo / Card)'), ('cash_on_delivery', 'Cash on Delivery'), ('momo', 'Mobile Money (MTN/Telecel/AT) — legacy'), ('card', 'Debit / Credit Card — legacy')], default='paystack', max_length=30),
        ),
    ]
