# Generated by Django 6.0.4 on 2026-09-17 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5),
        ),
        migrations.CreateModel(
            name='DeliveryOTPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=4)),
                ('buyer_notified_at', models.DateTimeField(blank=True, null=True)),
                ('buyer_notification_method', models.CharField(blank=True, default='sms+email', max_length=20)),
                ('code', models.CharField(max_length=4)),
                ('buyer_notified', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otp_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_log', to='orders.order')),
            ],
            options={
                'db_table': 'delivery_otp_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DeliveryPinLog',
        ),
    ]
