# Generated by Django 6.0.4 on 2026-09-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_commission_rate_orderitem_commission_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryotplog',
            name='code',
        ),
        migrations.RemoveField(
            model_name='deliveryotplog',
            name='driver',
        ),
    ]
