# Generated by Django 6.0.4 on 2026-09-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_emaillog_actual_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryotplog',
            name='buyer_notification_method',
            field=models.CharField(blank=True, default='email', max_length=20),
        ),
    ]
