# Generated by Django 6.0.4 on 2026-09-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_deliveryotplog_buyer_notification_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='seller_net_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
