# Generated by Django 6.0.4 on 2026-10-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_seller_net_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_collected',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
