# Generated by Django 6.0.4 on 2026-10-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_fix_otp_security'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryotplog',
            name='otp_expires_at',
            field=models.DateTimeField(),
        ),
    ]
