# Generated by Django 6.0.4 on 2026-10-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_guest_email_order_guest_name_order_guest_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryotplog',
            name='otp_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
