# Generated by Django 6.0.4 on 2026-10-02 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_deliveryotplog_otp_encrypted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='needs_driver',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='self_delivery_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='settlement',
            name='delivery_share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='SellerHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='orders.order')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoffs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seller_handoffs',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('order', 'seller'), name='unique_handoff_per_seller_order')],
            },
        ),
    ]
