# Generated by Django 6.0.4 on 2026-10-05 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_delivery_breakdown_order_needs_driver_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payout',
        ),
    ]
