# Generated by Django 6.0.4 on 2026-10-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_delete_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
