# Generated by Django 6.0.4 on 2026-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seller_average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seller_total_products',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seller_total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seller_total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customuser',
            name='seller_total_sales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='store_banner',
            field=models.ImageField(blank=True, null=True, upload_to='store_banners/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='store_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='store_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='store_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Buyer'), ('driver', 'Driver'), ('seller', 'Seller')], default='buyer', max_length=10),
        ),
    ]
