# Generated by Django 6.0.4 on 2026-09-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seller_store_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seller_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
