# Generated by Django 6.0.4 on 2026-09-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_seller_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sales_record_sent',
            field=models.BooleanField(default=False),
        ),
    ]
