# Generated by Django 6.0.4 on 2026-09-28 02:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seller_payout_subaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text="Commission percentage (0.00-30.00%). Buyers pay this on top of seller's listed price.", max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(30.0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='commission_rate_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CommissionRateAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(blank=True)),
                ('affected_products_count', models.IntegerField(default=0)),
                ('apply_to_existing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_rate_changes_made', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rate_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commission_rate_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
