# Generated by Django 6.0.4 on 2026-10-02 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Flat delivery fee per order when self-delivering (0.00-50.00 GHS).', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50.0)]),
        ),
        migrations.AddField(
            model_name='customuser',
            name='delivery_mode',
            field=models.CharField(choices=[('platform', 'Platform delivery'), ('self', 'Self delivery')], default='platform', max_length=20),
        ),
    ]
