# Generated by Django 6.0.4 on 2026-10-05 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_custom_delivery_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='seller_balance',
        ),
    ]
