# Generated by Django 6.0.4 on 2026-10-07 04:28

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_facebook_url_customuser_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[apps.core.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ghana_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='ghana_cards/', validators=[apps.core.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/', validators=[apps.core.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='store_banner',
            field=models.ImageField(blank=True, null=True, upload_to='store_banners/', validators=[apps.core.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='store_logos/', validators=[apps.core.validators.validate_image_file_size]),
        ),
    ]
