# Generated by Django 6.0.4 on 2026-10-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='fit',
            field=models.CharField(blank=True, choices=[('runs_small', 'Runs small'), ('true_to_size', 'True to size'), ('runs_large', 'Runs large')], default='', max_length=20),
        ),
    ]
