# Generated by Django 6.0.4 on 2026-10-07 04:28

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_fit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to='review_images/', validators=[apps.core.validators.validate_image_file_size]),
        ),
    ]
