# Generated by Django 6.0.4 on 2026-06-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_external_url_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='external_url',
            field=models.URLField(blank=True),
        ),
    ]
