# Generated by Django 6.0.4 on 2026-09-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Commission rate locked at listing time. Null = use seller's current rate.", max_digits=5, null=True),
        ),
    ]
