# Generated by Django 6.0.4 on 2026-10-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_commission_rate_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
