"""Mark every historically-seeded catalog row as demo/showcase.

Seed rows were created before the is_demo flag existed, so they carry
is_demo=False and would otherwise stay purchasable. Matches by exact
slug against BOTH seed files (command + legacy script), so vendor
products (never in seed lists) are untouched.
"""
from django.db import migrations


SEED_SLUGS = (
    'accessories',
    'ankara-print-dress',
    'ankle-boots-women',
    'asymmetric-hem-dress',
    'athletic-jogger-pants',
    'athletic-shorts-men',
    'aviator-sunglasses',
    'beaded-bracelet-set',
    'biker-shorts-women',
    'blazer-dress-women',
    'bodycon-mini-dress',
    'bomber-jacket-men',
    'boys-suit-set',
    'bucket-hat',
    'button-down-shirt-dress',
    'canvas-tote-bag',
    'cargo-pants-women',
    'cargo-shorts-men',
    'chain-bracelet',
    'chelsea-boots-men',
    'chelsea-boots-women',
    'chunky-knit-sweater-women',
    'classic-oxford-shoes',
    'classic-watch',
    'classic-white-linen-shirt',
    'compression-tights-men',
    'corduroy-trousers-men',
    'cowl-neck-dress',
    'crochet-cover-up',
    'crop-blazer-women',
    'cropped-knit-cardigan',
    'cuban-collar-shirt',
    'cufflinks-set',
    'cut-out-swimsuit',
    'dad-hat',
    'denim-jacket',
    'embroidered-kurta',
    'flannel-shirt-men',
    'flare-jeans-women',
    'flat-sandals',
    'floral-wrap-dress',
    'formal-waistcoat',
    'formal-white-dress-shirt',
    'girls-party-dress',
    'gold-hoop-earrings',
    'graphic-tee-men',
    'gym-duffel-bag',
    'henley-long-sleeve',
    'high-top-sneakers',
    'high-waist-denim-jeans',
    'jogger-set-women',
    'kente-bow-tie',
    'kente-print-shorts',
    'kids',
    'kids-ankara-outfit',
    'kids-colourful-tee-pack',
    'kids-denim-overalls',
    'kids-denim-shorts',
    'kids-graphic-tee',
    'kids-hoodie',
    'kids-polo-shirt',
    'kids-pyjama-set',
    'kids-rain-jacket',
    'kids-sandals',
    'kids-school-uniform',
    'kids-sneakers',
    'kids-summer-dress',
    'kids-swim-set',
    'kids-tracksuit',
    'kids-winter-coat',
    'knitted-beanie',
    'knitted-cardigan-men',
    'kofi-hat',
    'laptop-bag',
    'leather-backpack',
    'leather-belt',
    'leather-crossbody-bag',
    'leather-trousers-women',
    'leather-wallet',
    'linen-coord-set',
    'linen-trousers-men',
    'longline-cardigan-women',
    'longline-tshirt',
    'maxi-boho-dress',
    'men',
    'merino-crewneck-sweater',
    'mesh-panel-leggings',
    'mini-shorts-women',
    'mini-shoulder-bag',
    'off-shoulder-top',
    'oversized-denim-shirt-women',
    'oversized-hoodie',
    'platform-sneakers',
    'pleated-midi-skirt',
    'polarised-sunglasses',
    'printed-ankara-shirt',
    'printed-boardshorts',
    'puffer-jacket-women',
    'quarter-zip-pullover',
    'raffia-basket-bag',
    'relaxed-fit-shorts-men',
    'relaxed-linen-shirt-men',
    'ribbed-knit-dress',
    'ruched-midi-dress',
    'running-shoes',
    'satin-slip-dress',
    'silk-evening-blouse',
    'silk-pocket-square',
    'silk-scarf',
    'slim-fit-chinos',
    'slim-fit-suit',
    'slip-on-sneakers',
    'smart-casual-loafers',
    'smart-watch',
    'sports-bra-set',
    'statement-necklace',
    'strapless-bandeau-top',
    'strappy-heels',
    'straw-sun-hat',
    'striped-polo-shirt',
    'swim-shorts-men',
    'tailored-black-blazer',
    'tailored-blazer-women',
    'tie-collection',
    'track-jacket-men',
    'trench-coat-women',
    'turtleneck-sweater-men',
    'tweed-sport-coat',
    'utility-jacket-men',
    'v-neck-tshirt-pack',
    'waist-bag',
    'wide-leg-trousers-women',
    'women',
    'wool-blend-overcoat',
    'wrap-jumpsuit',
)


def mark_demo(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product.objects.filter(slug__in=SEED_SLUGS, is_demo=False).update(is_demo=True)


def unmark_demo(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product.objects.filter(slug__in=SEED_SLUGS, is_demo=True).update(is_demo=False)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_demo'),
    ]

    operations = [
        migrations.RunPython(mark_demo, unmark_demo),
    ]
