# Generated by Django 6.0.4 on 2026-10-07 04:28

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_mark_seed_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', validators=[apps.core.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[apps.core.validators.validate_image_file_size]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/', validators=[apps.core.validators.validate_image_file_size]),
        ),
    ]
